services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mei-calculadora:latest
    container_name: mei-calculadora

    # força o Streamlit a rodar na mesma porta que expomos
    environment:
      - PORT=8501

    ports:
      - "8501:8501"

    volumes:
      - .:/app

    command:
      - streamlit
      - run
      - app_streamlit.py
      - --server.port
      - "${PORT}"
      - --server.address
      - "0.0.0.0"

    stdin_open: true
    tty: true
    restart: unless-stopped
